language: ruby
rvm:
  - 1.8
  - 1.9
  - 2.0.0
  - 2.1.2
# bundler_args: --jobs=2

before_script:
 - chmod +x midi-test.sh midi-after-test.sh
script:
 - ./midi-test.sh && rake build
# - rake build
after_script:
 - ./midi-after-test.sh
branches:
  only:
    - master
