#!/usr/bin/ruby
# -*- encoding: utf-8 -*-
#
# on vector software library
# http://www.vector.co.jp/soft/dl/winnt/art/se508417.html

# the inputfile must be hex digit data string file generated by smml etc.
# comments are after '#' and those will be ignored.
# when edit it by hand, you have to study and follow SMF format.


DOREMI_STUDY_VERSION="0.1.2"

Encoding.default_external = 'UTF-8' if defined? Encoding

if ARGV.size<2
  # puts "usage: #{$0} hexStrfile out.mid"
end
mode,inf,of=ARGV[0..2]
inf,of="doremi_blank4.txt","out.mid" if inf==nil
mode="major" if mode==nil
da=(File.readlines(inf).map{|i|i.chomp.sub(/#.*/){}}-[""])*""

def note mode="major"
  c=0x3c
  r=rand(12)
  case mode
  when /^major/
    r=rand(12) while [1,3,6,8,10].member?(r)
  when /^minor/
    r=rand(12) while [1,4,6,9,11].member?(r)
  when /^chro(matic)/
    # r=rand(12)
  end
  "  #{format"%02X",r+c}  "
end
def hex2note0 n,doremi=true
  note=n.to_i(16)-0x3c
  scale=["c","c#","d","d#","e","f","f#","g","g#","a","a#","b","c"]
  scale=["do","do#","re","re#","mi","fa","fa#","sol","sol#","la","la#","si","do"] if doremi
  scale[note]
end
def hex2note n,doremi=true
  note=n.to_i(16)-0x3c
  scale=["C  | C","C# | Db","D  | D","D# | Eb","E  | E","F  | F","F# | Gb","G  | G","G# | Ab","A  | A","A# | Bb","B  | B","C  | C"]
  scale=["do   | do","do#  | re-","re   | re","re#  | mi-","mi   | mi","fa   | fa","fa#  | sol-","sol  | sol","sol# | la-","la   | la","la#  | si-","si   | si","do   | do"] if doremi
  scale[note]
end

ans=[]
n=4
n.times{|i|
  s=note(mode)
  ans<<s
  da.gsub!("__sound_#{i+1}__"){s}
}

open(of,"wb"){|o|
  o.write [da.split.join].pack( "H*" )
}
open("ans.txt","w"){|o|
  o.puts ans.map{|i|hex2note(i)}
}